# Generated by Django 4.1.5 on 2023-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_column='Position', max_length=40)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=8)),
                ('work_schedule', models.CharField(db_column='Work_schedule', max_length=40)),
                ('responsibilities', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Описание')),
                ('working_conditions', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]

